### ISSUE TITLE
rog-widget-oah

### ISSUE THREAD

**Issue by OmarEng** [Roche/ROGeTMF#2]
Hello, I have problems to compile the module rog-publicsearches-widget because it's missing the dependency rog-widget-oah, could you please help me?
Thank you.

Omar

**Comment by krzysztof-jurkowski-roche** [comment]
This should be rog-publicsearches-oah instead. I fixed this in the pom inside rog-publicsearches-widget.
Please let me know if it works fine for you.

**Comment by OmarEng** [comment]
Thank you. I've also changed the groupId of freemarker in org.freemarker, maven install done successfully but when I import the project in Eclipse I found errors in class SearchToolbar for the module rog-publicsearches-widget (missing import for the class Message?) and in the class D2MenuServicePlugin for the module rog-publicsearches-d2-plugin (the type org.aspectj.lang.ProceedingJoinPoint cannot be resolved)

**Comment by krzysztof-jurkowski-roche** [comment]
This is a gwt project so, to compile i18n you have to call `mvn gwt:i18n`.
Also remember to add `target/generated-sources/gwt` in Java Build path in Eclipse project configuration.
